### ISSUE TITLE
L2RPacketReader.exe

### ISSUE THREAD

**Issue by Groffitti** [AngryHank/Lin2RevJunk#5]
After I click L2RPacketReader.exe the cmd prompt comes up for a second then closes. I can't seem to find whats wrong.

![untitled-2](https://user-images.githubusercontent.com/40250522/41381356-8014fd52-6f35-11e8-81cb-26e056570f3d.jpg)

**Comment by AMiniLegend** [comment]
You need to install winpcap

**Comment by Groffitti** [comment]
I figured it out. Thanks for getting back to me.

**Comment by AMiniLegend** [comment]
No problem

**Comment by Gherik1** [comment]
I just tried this but when checking the roster while the packed sniffer it running I get:

Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at L2RPacketReader.PacketReader.ReadString()
   at L2RPacketReader.Parser.Parsers.PktGuildInfoReadresult.Packet(PacketReader packet)
   at L2RPacketReader.Parser.Handler.Parse(PacketReader packet, UInt16 packetID)
   at L2RPacketReader.RecordPackets.AppendIncomingData(Byte[] payloadData)
   at L2RPacketReader.RecordPackets.PacketCapturer(Object sender, CaptureEventArgs e)
   at SharpPcap.LibPcap.PcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.WinPcap.WinPcapDevice.SendPacketArrivalEvent(RawCapture p)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.LibPcapSafeNativeMethods.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
